# Assigning tasks to specific hosts

-
  hosts: 172.31.17.60
  name: play1
  
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible

    - name: install tree
      yum:
        name: tree
        state: present
- 
  name: Play2
  hosts: 172.31.17.60
  tasks:
    - name: install git
      yum:
        name: git
        state: present


